---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: print-headers
    app.kubernetes.io/component: print-headers
    app.kubernetes.io/instance: print-headers
  name: print-headers
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentconfig: print-headers
  sessionAffinity: None
  type: ClusterIP
