apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customer-namespace-2
  namespace: managed-hosting-admin
  labels:
    app.kubernetes.io/instance: seed
spec:
  destination:
    namespace: managed-hosting-admin
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: customer-namespace-2
    repoURL: 'https://github.com/jeichler/argo-demo.git'
    targetRevision: main
  syncPolicy:
    automated: {}
